### ISSUE TITLE
GetCentroidList() and GetCentrOInpList() return inconsistent data.

### ISSUE THREAD

**Issue by bbogart** [ANNetGPGPU/ANNetGPGPU#4]
Lines 409 to 412 in SOMNet.cpp do the following:

`// Count the number of centroids
std::sort(vCentroids.begin(), vCentroids.end() );
vCentroids.erase(std::unique(vCentroids.begin(), vCentroids.end()), vCentroids.end() );
std::cout<<"Number of clusters found: "<<vCentroids.size()<<std::endl;`

Which, of course, messes up both the order of the centroids (by sorting) and removes centroids with the same values. I don't think the resulting vCentroids has any meaning after this processing and makes the behaviour of GetCentroidList() and GetCentrOInpList() inconsistent!

I think this is probably just a bug and these lines should be removed, or vCentroids should be copied into a new var before the centroid "count".

**Comment by dgrat** [comment]
Should be resolved

**Comment by bbogart** [comment]
I just did a fresh clone and the offending code is still there.
